#!/usr/bin/env bash
set -euo pipefail

# Mirror the Claude Code setup into OpenAI Codex so the same skills and project
# instructions work in both tools.
#
# What this does (all idempotent, safe to re-run):
#   1. Links every global skill in dotfiles/claude/skills into ~/.codex/skills
#   2. Links the brain repo's project-local skills into ~/.codex/skills
#      (Codex only discovers skills globally, so project skills become global)
#   3. Creates AGENTS.md -> CLAUDE.md symlinks in the brain repo so Codex reads
#      the same project instructions Claude Code does
#   4. Flattens the global Claude config (dotfiles/claude/CLAUDE.md + every
#      @rules/*.md it imports, recursively) into ~/.codex/AGENTS.md so Codex
#      honors the same global rules. Codex does not expand @-imports, so we
#      inline them here. Re-run this script after editing any rule file.
#
# It never touches ~/.codex/skills/.system (Codex-managed built-in skills).

DOTFILES_CLAUDE="$HOME/Developer/dotfiles/claude"
DOTFILES_SKILLS="$DOTFILES_CLAUDE/skills"
BRAIN="$HOME/Developer/brain"
BRAIN_SKILLS="$BRAIN/.claude/skills"
CODEX_HOME_DIR="${CODEX_HOME:-$HOME/.codex}"
CODEX_SKILLS="$CODEX_HOME_DIR/skills"

mkdir -p "$CODEX_SKILLS"

link_skill() {
  # $1 = absolute path to a skill folder, $2 = destination dir
  local src="$1" dst_dir="$2"
  local name
  name="$(basename "$src")"
  [[ "$name" == _* ]] && return 0          # skip shared/helper folders
  [[ -f "$src/SKILL.md" ]] || return 0     # only real skills
  ln -sfn "$src" "$dst_dir/$name"
}

echo "==> Linking global dotfiles skills into $CODEX_SKILLS"
global_count=0
for skill in "$DOTFILES_SKILLS"/*/; do
  link_skill "${skill%/}" "$CODEX_SKILLS" && global_count=$((global_count + 1))
done
echo "    linked $global_count global skills"

echo "==> Linking brain project skills into $CODEX_SKILLS (skipping name collisions)"
brain_count=0
skipped=()
for skill in "$BRAIN_SKILLS"/*/; do
  name="$(basename "${skill%/}")"
  [[ "$name" == _* ]] && continue
  [[ -f "${skill%/}/SKILL.md" ]] || continue
  # Skip if a global dotfiles skill already owns this name (can't have two)
  if [[ -e "$DOTFILES_SKILLS/$name" ]]; then
    skipped+=("$name")
    continue
  fi
  link_skill "${skill%/}" "$CODEX_SKILLS" && brain_count=$((brain_count + 1))
done
echo "    linked $brain_count brain skills"
if ((${#skipped[@]})); then
  echo "    skipped (name already used by a global skill): ${skipped[*]}"
fi

echo "==> Creating AGENTS.md symlinks in the brain repo"
# Codex reads AGENTS.md; point it at the existing CLAUDE.md files.
make_agents_link() {
  # $1 = directory, $2 = actual CLAUDE filename in that dir
  local dir="$1" claude="$2"
  local target="$dir/AGENTS.md"
  if [[ -e "$target" && ! -L "$target" ]]; then
    echo "    WARN: $target exists and is not a symlink; leaving it alone"
    return 0
  fi
  ( cd "$dir" && ln -sfn "$claude" AGENTS.md )
  echo "    $target -> $claude"
}
[[ -f "$BRAIN/CLAUDE.MD" ]]        && make_agents_link "$BRAIN" "CLAUDE.MD"
[[ -f "$BRAIN/fiction/CLAUDE.md" ]] && make_agents_link "$BRAIN/fiction" "CLAUDE.md"

echo "==> Flattening global Claude config into $CODEX_HOME_DIR/AGENTS.md"
# Codex does not expand Claude's @path imports, so resolve them recursively
# and inline every referenced rule file into one generated AGENTS.md.
CODEX_AGENTS="$CODEX_HOME_DIR/AGENTS.md" python3 - "$DOTFILES_CLAUDE/CLAUDE.md" <<'PY'
import os, re, sys

root = os.path.abspath(sys.argv[1])
out_path = os.environ["CODEX_AGENTS"]
home = os.path.expanduser("~")
ref_re = re.compile(r'@([~./A-Za-z0-9_-]+\.md)')

def resolve(ref, base_dir):
    if ref.startswith("~/"):
        return os.path.abspath(os.path.join(home, ref[2:]))
    return os.path.abspath(os.path.join(base_dir, ref))

seen, order = set(), []

def walk(path):
    path = os.path.abspath(path)
    if path in seen or not os.path.isfile(path):
        return
    # Skip skill files; skills are loaded on demand in both tools.
    if os.path.basename(path) == "SKILL.md" or f"{os.sep}skills{os.sep}" in path:
        return
    seen.add(path)
    text = open(path, encoding="utf-8").read()
    order.append((path, text))
    for m in ref_re.findall(text):
        walk(resolve(m, os.path.dirname(path)))

walk(root)

parts = [
    "<!-- GENERATED by dotfiles/machine-setup/link-codex.sh — do not edit by hand. -->",
    "<!-- Mirrors the global Claude Code config so Codex honors the same rules. -->",
    "<!-- Re-run the script after editing any source rule file. -->",
    "",
]
for i, (path, text) in enumerate(order):
    rel = os.path.relpath(path, os.path.dirname(root))
    if i > 0:
        parts.append(f"\n\n<!-- imported from {rel} -->\n")
    parts.append(text.rstrip())

open(out_path, "w", encoding="utf-8").write("\n".join(parts) + "\n")
print(f"    wrote {out_path} ({len(order)} files inlined)")
PY

echo "==> Done."
