#!/usr/bin/env bash
set -euo pipefail

# Mirror the Claude Code setup into OpenAI Codex so the same skills and project
# instructions work in both tools.
#
# What this does (all idempotent, safe to re-run):
#   1. Links every canonical skill into ~/.codex/skills. The canonical directory
#      is ~/Developer/brain/skills; there is no second source any more. Codex
#      only discovers skills globally, so every skill becomes global.
#   2. Creates AGENTS.md -> CLAUDE.md symlinks in the brain repo so Codex reads
#      the same project instructions Claude Code does
#   3. Flattens the global Claude config (dotfiles/claude/CLAUDE.md + every
#      @rules/*.md it imports, recursively) into ~/.codex/AGENTS.md so Codex
#      honors the same global rules. Codex does not expand @-imports, so we
#      inline them here. Re-run this script after editing any rule file.
#
# It never touches ~/.codex/skills/.system (Codex-managed built-in skills).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DOTFILES_CLAUDE="$REPO_ROOT/claude"
BRAIN="${BRAIN:-$(cd "$REPO_ROOT/.." && pwd)/brain}"
CANONICAL_SKILLS="${SKILLS_CANONICAL:-$BRAIN/skills}"
CODEX_HOME_DIR="${CODEX_HOME:-$HOME/.codex}"
CODEX_SKILLS="$CODEX_HOME_DIR/skills"

echo "==> Linking canonical skills into $CODEX_SKILLS"
LINK_SKILLS="$BRAIN/scripts/link-skills.sh"
if [[ -x "$LINK_SKILLS" ]]; then
  # The canonical installer knows how to resolve a skill the skills CLI owns to
  # its real directory, so no chains form and nothing gets linked to itself.
  "$LINK_SKILLS" --target "$CODEX_SKILLS" \
    || echo "    link-skills.sh reported items needing a decision. See above."
else
  echo "    WARN: $LINK_SKILLS not found; falling back to a plain link pass"
  mkdir -p "$CODEX_SKILLS"
  count=0
  for skill in "$CANONICAL_SKILLS"/*/; do
    name="$(basename "${skill%/}")"
    case "$name" in _*) continue ;; esac
    [[ -f "${skill%/}/SKILL.md" ]] || continue
    target="$(cd -P "${skill%/}" && pwd -P)"
    ln -sfn "$target" "$CODEX_SKILLS/$name"
    count=$((count + 1))
  done
  echo "    linked $count skills"
fi

echo "==> Creating AGENTS.md symlinks in the brain repo"
# Codex reads AGENTS.md; point it at the existing CLAUDE.md files.
make_agents_link() {
  # $1 = directory, $2 = actual CLAUDE filename in that dir
  local dir="$1" claude="$2"
  local target="$dir/AGENTS.md"
  if [[ -e "$target" && ! -L "$target" ]]; then
    echo "    WARN: $target exists and is not a symlink; leaving it alone"
    return 0
  fi
  ( cd "$dir" && ln -sfn "$claude" AGENTS.md )
  echo "    $target -> $claude"
}
if [[ -f "$BRAIN/CLAUDE.MD" ]]; then make_agents_link "$BRAIN" "CLAUDE.MD"; fi
if [[ -f "$BRAIN/fiction/CLAUDE.md" ]]; then make_agents_link "$BRAIN/fiction" "CLAUDE.md"; fi

echo "==> Flattening global Claude config into $CODEX_HOME_DIR/AGENTS.md"
# Codex does not expand Claude's @path imports, so resolve them recursively
# and inline every referenced rule file into one generated AGENTS.md.
CODEX_AGENTS="$CODEX_HOME_DIR/AGENTS.md" python3 - "$DOTFILES_CLAUDE/CLAUDE.md" <<'PY'
import os, re, sys

root = os.path.abspath(sys.argv[1])
out_path = os.environ["CODEX_AGENTS"]
home = os.path.expanduser("~")
ref_re = re.compile(r'@([~./A-Za-z0-9_-]+\.md)')

def resolve(ref, base_dir):
    if ref.startswith("~/"):
        return os.path.abspath(os.path.join(home, ref[2:]))
    return os.path.abspath(os.path.join(base_dir, ref))

seen, order = set(), []

def walk(path):
    path = os.path.abspath(path)
    if path in seen or not os.path.isfile(path):
        return
    # Skip skill files; skills are loaded on demand in both tools.
    if os.path.basename(path) == "SKILL.md" or f"{os.sep}skills{os.sep}" in path:
        return
    seen.add(path)
    text = open(path, encoding="utf-8").read()
    order.append((path, text))
    for m in ref_re.findall(text):
        walk(resolve(m, os.path.dirname(path)))

walk(root)

parts = [
    "<!-- GENERATED by dotfiles/machine-setup/link-codex.sh — do not edit by hand. -->",
    "<!-- Mirrors the global Claude Code config so Codex honors the same rules. -->",
    "<!-- Re-run the script after editing any source rule file. -->",
    "",
]
for i, (path, text) in enumerate(order):
    rel = os.path.relpath(path, os.path.dirname(root))
    if i > 0:
        parts.append(f"\n\n<!-- imported from {rel} -->\n")
    parts.append(text.rstrip())

open(out_path, "w", encoding="utf-8").write("\n".join(parts) + "\n")
print(f"    wrote {out_path} ({len(order)} files inlined)")
PY

echo "==> Done."
