#!/usr/bin/env python3
"""Generate Codex agent configs from the Claude Code agent definitions.

Reads every claude/agents/*.md with frontmatter and writes
~/.codex/agents/<name>.toml with name, description, and developer_instructions.
CLAUDE.md becomes AGENTS.md and "Claude Code" / "Claude" become "Codex", so the
instructions point at the files Codex reads. Generated files carry a header
line; a generated file whose source agent is gone is deleted. Files without
the header are never touched.

Usage: scripts/sync-codex-agents.py   (re-run after editing any agent)
"""

from __future__ import annotations

import os
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / "claude" / "agents"
CODEX_AGENTS = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")) / "agents"
HEADER = "# Generated by dotfiles/scripts/sync-codex-agents.py. Edit claude/agents/ instead."


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Split a Markdown agent file into its simple YAML frontmatter and body."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.index("\n---", 4)
    lines = text[4:end].splitlines()
    fields: dict[str, str] = {}
    i = 0
    while i < len(lines):
        match = re.match(r"^([A-Za-z_-]+):\s*(.*)$", lines[i])
        i += 1
        if not match:
            continue
        key, value = match.group(1), match.group(2).strip()
        if value in (">", "|", ">-", "|-"):
            block = []
            while i < len(lines) and (lines[i].startswith(" ") or not lines[i].strip()):
                block.append(lines[i].strip())
                i += 1
            value = " ".join(part for part in block if part)
        fields[key] = value.strip().strip('"')
    return fields, text[end + 4 :].lstrip("\n")


def to_codex(text: str) -> str:
    """Point Claude-specific file and product names at their Codex equivalents."""
    text = text.replace("CLAUDE.md", "AGENTS.md")
    text = re.sub(r"\bClaude Code\b", "Codex", text)
    return re.sub(r"(?<![/\w.])Claude\b", "Codex", text)


def toml_basic(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return '"""\n' + escaped + '"""'


def render(fields: dict[str, str], body: str) -> str:
    return "\n".join(
        [
            HEADER,
            f"name = {toml_basic(fields['name'])}",
            f"description = {toml_basic(to_codex(fields['description']))}",
            f"developer_instructions = {toml_multiline(to_codex(body))}",
            "",
        ]
    )


def main() -> int:
    CODEX_AGENTS.mkdir(parents=True, exist_ok=True)
    written: set[str] = set()
    for source in sorted(SOURCE_DIR.glob("*.md")):
        fields, body = parse_frontmatter(source.read_text())
        if "name" not in fields or "description" not in fields:
            continue
        output = render(fields, body)
        parsed = tomllib.loads(output)
        if parsed["developer_instructions"] != to_codex(body):
            print(f"error: TOML round trip changed {source.name}", file=sys.stderr)
            return 1
        target = CODEX_AGENTS / f"{fields['name']}.toml"
        target.write_text(output)
        written.add(target.name)
        print(f"wrote   {target}")
    for stale in sorted(CODEX_AGENTS.glob("*.toml")):
        if stale.name not in written and stale.read_text().startswith(HEADER):
            stale.unlink()
            print(f"removed {stale}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
